---
-
  dag_name: jiuzhang
  concurrency: 1
  max_active_runs: 1
  template: spark-job.py.j2
  schedule_interval: "@daily"
  start_date: 2019-03-26 00:00:00
  job:
    jar: gs://jiuzhangsuanfa/SparkProject-assembly-0.1.jar
    main_class: com.jiuzhang.spark.LoanAnalyze
    name: loan
    args: |
      ["gs://jiuzhangsuanfa/LendingClub/LoanStats_2019Q1.csv",
       "gs://jiuzhangsuanfa/LendingClub/RejectStats_2019Q1.csv",
       "gs://jiuzhangsuanfa/output"]
